steps:
- name: 'gcr.io/cloud-builders/docker'

runtime: python37

handlers:

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /static
  static_dir: static/


- url: /.*
  script: auto

error_handlers:
 - file: 404.html
