# Generated by Django 2.1.3 on 2019-08-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook',
            name='icon_link',
            field=models.CharField(default='fas fa-home', max_length=20),
            preserve_default=False,
        ),
    ]
