# Generated by Django 2.1.3 on 2019-07-31 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='rulebook',
        ),
        migrations.AddField(
            model_name='rule',
            name='parent_rulebook',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='hr.Rulebook'),
        ),
        migrations.AddField(
            model_name='rulebook',
            name='parent_house',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='hr.House'),
        ),
    ]
