# Generated by Django 2.1.3 on 2019-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20190816_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulebook',
            name='icon_link',
        ),
        migrations.AddField(
            model_name='house',
            name='qr_code',
            field=models.ImageField(default='default-qr.jpg', upload_to='images/qr_codes'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
