# Generated by Django 2.1.3 on 2019-07-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20190731_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulebook',
            old_name='name_text',
            new_name='rulebook_name',
        ),
    ]
