# Generated by Django 2.1.3 on 2019-10-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20190922_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='icon_link',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='parent_rulebook',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='hr.Rulebook'),
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='parent_house',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, related_name='rulebooks', to='hr.House'),
        ),
    ]
